### ISSUE TITLE
Add Jisho preview to landing page

### ISSUE THREAD

**Issue by karenin-overseas** [karenin-overseas/ngw#4]
Add Jisho preview box with top most-common definition of word highlighted
to the landing page.

Add large word preview box to landing page.

Two cards?
Word -- Romanji
Most common Jisho definition

Basically gives same functionality as Rikai-chan chrome extension, except 
is not a chrome extension.

Do not clutter landing page with >1 Jisho definition; this is too much information for most users to process

**Comment by caroline-lin** [comment]
Ok, figured out how to do this.

The Jisho server is configured s.t. making a GET request to the API from localhost => CORS error :(

Lots of people on the API page have same issue:
https://jisho.org/forum/54fefc1f6e73340b1f160000-is-there-any-kind-of-search-api

This uses a proxy server hosted on heroku that is configured to sidestep CORS:
https://cors-anywhere.herokuapp.com/

Can use wget to access cors-anywhere, e.g

> wget "https://cors-anywhere.herokuapp.com/https://jisho.org/api/v1/search/words?keyword=風" --header="Origin:Nope"


Aside: wget also works out of the box here:

> wget "https://jisho.org/api/v1/search/words?keyword=風"

wget saves the output to a file automatically.

Also updated my node version to browse wget's output in fname:
Node 12.4.0

let fs = require('fs')
fs.readFileSync(fname)
JSON.parse(_)

Next step is to try a cors-anywhere in my app.
